#!/usr/bin/env python3
"""Audit Rev A KiCad capture progress against the project manifests."""

from __future__ import annotations

import argparse
import csv
import re
import sys
from collections import defaultdict
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
SYMBOL_MANIFEST = SCRIPT_DIR / "rev-a-symbol-manifest.csv"
NET_MANIFEST = SCRIPT_DIR / "rev-a-net-label-manifest.csv"
DEFAULT_REPORT = SCRIPT_DIR / "rev-a-capture-audit.md"

SCHEMATIC_FILES = {
    "top-level": SCRIPT_DIR / "GAS-Hardware.kicad_sch",
    "io-board": SCRIPT_DIR / "io-board.kicad_sch",
    "tank-driver-recovery": SCRIPT_DIR / "tank-driver-recovery.kicad_sch",
    "ext-tank-routing": SCRIPT_DIR / "ext-tank-routing.kicad_sch",
    "crossfade-feedback-wet": SCRIPT_DIR / "crossfade-feedback-wet.kicad_sch",
    "filter-clipper": SCRIPT_DIR / "filter-clipper.kicad_sch",
    "power-backplane": SCRIPT_DIR / "power-backplane.kicad_sch",
}

REFERENCE_PATTERN = re.compile(r'\(property\s+"Reference"\s+"([^"]+)"')
LABEL_PATTERN = re.compile(r'\((?:global_label|label|hierarchical_label)\s+"([^"]+)"')
SHEETFILE_PATTERN = re.compile(r'\(property\s+"Sheetfile"\s+"([^"]+)"')


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_REPORT,
        help="Markdown report path. Default: %(default)s",
    )
    return parser.parse_args()


def read_csv_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def expand_reference_designators(refdes: str) -> list[str]:
    refdes = refdes.strip()
    match = re.fullmatch(r"([A-Za-z]+)(\d+)-([A-Za-z]+)?(\d+)", refdes)
    if not match:
        return [refdes]

    start_prefix, start_number, end_prefix, end_number = match.groups()
    end_prefix = end_prefix or start_prefix
    if start_prefix != end_prefix:
        return [refdes]

    start = int(start_number)
    end = int(end_number)
    if end < start:
        start, end = end, start

    width = max(len(start_number), len(end_number))
    return [f"{start_prefix}{value:0{width}d}" for value in range(start, end + 1)]


def parse_schematic(path: Path) -> dict[str, set[str]]:
    text = path.read_text(encoding="utf-8")
    return {
        "refs": set(REFERENCE_PATTERN.findall(text)),
        "labels": set(LABEL_PATTERN.findall(text)),
        "sheetfiles": set(SHEETFILE_PATTERN.findall(text)),
    }


def load_symbol_expectations() -> tuple[dict[str, set[str]], set[str], dict[str, set[str]]]:
    expected_refs: dict[str, set[str]] = defaultdict(set)
    optional_refs: dict[str, set[str]] = defaultdict(set)
    expected_sheetfiles: set[str] = set()

    for row in read_csv_rows(SYMBOL_MANIFEST):
        sheet_name = row["Sheet"].strip()
        status = row["Status"].strip().lower()

        if sheet_name == "top-level":
            expected_sheetfiles.add(row["ValueOrMPN"].strip())
            continue

        bucket = optional_refs if status == "optional" else expected_refs
        for ref in expand_reference_designators(row["RefDes"]):
            bucket[sheet_name].add(ref)

    return expected_refs, expected_sheetfiles, optional_refs


def load_net_expectations() -> dict[str, set[str]]:
    expected_labels: dict[str, set[str]] = defaultdict(set)
    for row in read_csv_rows(NET_MANIFEST):
        expected_labels[row["Scope"].strip()].add(row["NetLabel"].strip())
    return expected_labels


def make_summary_row(name: str, required: int, found: int, optional_found: int) -> str:
    percent = 100.0 if required == 0 else (found / required) * 100.0
    return f"| {name} | {found}/{required} | {percent:5.1f}% | {optional_found} |"


def main() -> int:
    args = parse_args()

    expected_refs, expected_sheetfiles, optional_refs = load_symbol_expectations()
    expected_labels = load_net_expectations()

    parsed = {name: parse_schematic(path) for name, path in SCHEMATIC_FILES.items()}
    found_project_labels = set().union(*(data["labels"] for data in parsed.values()))

    lines: list[str] = []
    lines.append("# GAS Rev A Capture Audit")
    lines.append("")
    lines.append(
        "Generated by "
        f"`python hardware/kicad/audit-rev-a-capture.py --output {args.output.as_posix()}`."
    )
    lines.append("")

    top_level_found_sheetfiles = parsed["top-level"]["sheetfiles"]
    missing_sheetfiles = sorted(expected_sheetfiles - top_level_found_sheetfiles)
    lines.append("## Top-Level Hierarchy")
    lines.append("")
    lines.append(
        f"- Hierarchical child sheets present: `{len(top_level_found_sheetfiles)}` / `{len(expected_sheetfiles)}`"
    )
    if missing_sheetfiles:
        lines.append(f"- Missing sheet files: `{', '.join(missing_sheetfiles)}`")
    else:
        lines.append("- Missing sheet files: none")
    lines.append("")

    lines.append("## Symbol Population")
    lines.append("")
    lines.append("| Sheet | Refs Found | Completion | Optional Refs Found |")
    lines.append("| --- | ---: | ---: | ---: |")

    for sheet_name in [name for name in SCHEMATIC_FILES if name != "top-level"]:
        required_refs = expected_refs.get(sheet_name, set())
        found_refs = parsed[sheet_name]["refs"] & required_refs
        found_optional = parsed[sheet_name]["refs"] & optional_refs.get(sheet_name, set())
        lines.append(
            make_summary_row(
                sheet_name,
                len(required_refs),
                len(found_refs),
                len(found_optional),
            )
        )
    lines.append("")

    lines.append("## Missing References By Sheet")
    lines.append("")
    for sheet_name in [name for name in SCHEMATIC_FILES if name != "top-level"]:
        required_refs = expected_refs.get(sheet_name, set())
        missing_refs = sorted(required_refs - parsed[sheet_name]["refs"])
        lines.append(f"### {sheet_name}")
        lines.append("")
        if missing_refs:
            lines.append(f"- Missing required refs: `{', '.join(missing_refs)}`")
        else:
            lines.append("- Missing required refs: none")
        optional_missing = sorted(optional_refs.get(sheet_name, set()) - parsed[sheet_name]["refs"])
        if optional_missing:
            lines.append(f"- Optional refs still absent: `{', '.join(optional_missing)}`")
        lines.append("")

    lines.append("## Net Label Coverage")
    lines.append("")
    lines.append("| Scope | Labels Found | Completion |")
    lines.append("| --- | ---: | ---: |")
    for scope_name in ["global", "io-boundary", "inter-board", "control"]:
        expected = expected_labels.get(scope_name, set())
        found = found_project_labels & expected
        percent = 100.0 if not expected else (len(found) / len(expected)) * 100.0
        lines.append(f"| {scope_name} | {len(found)}/{len(expected)} | {percent:5.1f}% |")
    lines.append("")

    lines.append("## Missing Net Labels")
    lines.append("")
    for scope_name in ["global", "io-boundary", "inter-board", "control"]:
        expected = expected_labels.get(scope_name, set())
        missing = sorted(expected - found_project_labels)
        lines.append(f"### {scope_name}")
        lines.append("")
        if missing:
            lines.append(f"- Missing labels: `{', '.join(missing)}`")
        else:
            lines.append("- Missing labels: none")
        lines.append("")

    lines.append("## Notes")
    lines.append("")
    lines.append(
        "- This audit intentionally measures only what is visible in the checked-in schematic text: "
        "sheet files, symbol reference designators, and explicit labels."
    )
    lines.append(
        "- It does not claim analog correctness, ERC cleanliness, or footprint completeness."
    )
    lines.append(
        "- A placeholder child sheet will therefore score `0%` until real symbols and labels are entered."
    )
    lines.append("")

    args.output.write_text("\n".join(lines), encoding="utf-8")

    total_required = sum(len(refs) for refs in expected_refs.values())
    total_found = sum(
        len(parsed[sheet]["refs"] & expected_refs.get(sheet, set()))
        for sheet in expected_refs
    )
    total_labels = sum(len(labels) for labels in expected_labels.values())
    found_labels = len(found_project_labels & set().union(*expected_labels.values()))

    print(
        f"Audit complete: refs {total_found}/{total_required}, "
        f"labels {found_labels}/{total_labels}, "
        f"report {args.output}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
