#!/usr/bin/env python3
"""Shared PCB generator for the GAS Rev A boards (generalized from gen_tdr_pcb.py).

build_board(...) writes a netlist-synced .kicad_pcb with footprints placed per a
layout map, board outline, M3 mounting holes, and solid AGND pours on both
copper layers. Routing is a separate pass (route_board.py)."""
import os
import gen_tdr as g

FP_DIR = r"C:\Program Files\KiCad\10.0\share\kicad\footprints"
GAS_DIR = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                        "..", "GAS.pretty"))

def merged_components(sections):
    parts = {}
    for _, cs in sections:
        for c in cs:
            ref = c["ref"].split("_")[0] if not c["ref"].startswith("#") else c["ref"]
            if ref.startswith("#"):
                continue
            p = parts.setdefault(ref, dict(ref=ref, fp=c["fp"], value=c["value"],
                                           dnp=c["dnp"], pads={}))
            for unit, netmap in c["units"].items():
                pins = g.symbol_pins(c["lib"], c["name"])
                upins = pins.get(unit, []) + pins.get(0, [])
                for num, name, _, _, _ in upins:
                    net = netmap.get(num) or netmap.get(name)
                    if net and net != "NC":
                        p["pads"][num] = net
    return parts

_fp_cache = {}

def load_footprint(fpid):
    if fpid in _fp_cache:
        return _fp_cache[fpid]
    lib, name = fpid.split(":")
    base = GAS_DIR if lib == "GAS" else os.path.join(FP_DIR, lib + ".pretty")
    with open(os.path.join(base, name + ".kicad_mod"), encoding="utf-8") as f:
        _fp_cache[fpid] = f.read()
    return _fp_cache[fpid]

def place_footprint(fpid, ref, value, x, y, rot, padnets, netcodes, dnp=False):
    sx = load_footprint(fpid)
    tree = g.parse(sx)[0]
    tree[1] = g.q(fpid)
    out = g.Sexp([t for t in tree if not (isinstance(t, g.Sexp) and t and
                                          t[0] in ("version", "generator", "generator_version"))])
    idx = 2
    for i, t in enumerate(out):
        if isinstance(t, g.Sexp) and t and t[0] == "layer":
            idx = i + 1
            break
    out.insert(idx, g.parse('(uuid "%s")' % g.uid())[0])
    out.insert(idx + 1, g.parse("(at %.3f %.3f %d)" % (x, y, rot))[0])
    if dnp:
        attr = g.find(out, "attr")
        if attr is not None:
            attr.append("dnp")
        else:
            out.insert(idx + 2, g.parse("(attr dnp)")[0])
    for t in out:
        if isinstance(t, g.Sexp) and t and t[0] == "property":
            if t[1] == '"Reference"':
                t[2] = g.q(ref)
            elif t[1] == '"Value"':
                t[2] = g.q(value)
        if isinstance(t, g.Sexp) and t and t[0] == "fp_text" and len(t) > 2:
            if t[1] == "reference":
                t[2] = g.q(ref)
            elif t[1] == "value":
                t[2] = g.q(value)
    if rot:
        for t in out:
            if isinstance(t, g.Sexp) and t and t[0] == "pad":
                at = g.find(t, "at")
                if at is not None:
                    if len(at) == 3:
                        at.append(str(rot))
                    else:
                        at[3] = str((float(at[3]) + rot) % 360)
    for t in out:
        if isinstance(t, g.Sexp) and t and t[0] == "pad":
            num = t[1].strip('"')
            if num in padnets:
                t.append(g.parse('(net %d "%s")' % (netcodes[padnets[num]],
                                                    padnets[num]))[0])
            t.append(g.parse('(uuid "%s")' % g.uid())[0])
    return g.dump(out, 1)

def build_board(parts, pos, out_path, board_w, board_h, title,
                gnd_net="AGND", ox=30.0, oy=30.0, hole_inset=6.0):
    missing = [r for r in parts if r not in pos]
    if missing:
        raise SystemExit("no layout position for: %s" % ", ".join(sorted(missing)))
    nets = sorted({n for p in parts.values() for n in p["pads"].values()})
    netcodes = {n: i + 1 for i, n in enumerate(nets)}

    hdr = ['(kicad_pcb', '\t(version 20260206)', '\t(generator "pcbnew")',
           '\t(generator_version "10.0")',
           '\t(general\n\t\t(thickness 1.6)\n\t\t(legacy_teardrops no)\n\t)',
           '\t(paper "A3")',
           '\t(title_block\n\t\t(title "%s")\n\t\t(company "Illicit Apothecary")'
           '\n\t\t(comment 1 "Generated by hardware/kicad/rebuild - edit the generator, not this file")\n\t)' % title,
           '\t(layers\n'
           '\t\t(0 "F.Cu" signal)\n\t\t(2 "B.Cu" signal)\n'
           '\t\t(9 "F.Adhes" user "F.Adhesive")\n\t\t(11 "B.Adhes" user "B.Adhesive")\n'
           '\t\t(13 "F.Paste" user)\n\t\t(15 "B.Paste" user)\n'
           '\t\t(5 "F.SilkS" user "F.Silkscreen")\n\t\t(7 "B.SilkS" user "B.Silkscreen")\n'
           '\t\t(1 "F.Mask" user)\n\t\t(3 "B.Mask" user)\n'
           '\t\t(17 "Dwgs.User" user "User.Drawings")\n\t\t(19 "Cmts.User" user "User.Comments")\n'
           '\t\t(21 "Eco1.User" user "User.Eco1")\n\t\t(23 "Eco2.User" user "User.Eco2")\n'
           '\t\t(25 "Edge.Cuts" user)\n\t\t(27 "Margin" user)\n'
           '\t\t(31 "F.CrtYd" user "F.Courtyard")\n\t\t(29 "B.CrtYd" user "B.Courtyard")\n'
           '\t\t(35 "F.Fab" user)\n\t\t(33 "B.Fab" user)\n\t)',
           '\t(setup\n\t\t(pad_to_mask_clearance 0)\n\t\t(allow_soldermask_bridges_in_footprints no)\n'
           '\t\t(tenting front back)\n'
           '\t\t(pcbplotparams\n\t\t\t(layerselection 0x00000000_00000000_55555555_5755f5ff)\n'
           '\t\t\t(plot_on_all_layers_selection 0x00000000_00000000_00000000_00000000)\n'
           '\t\t\t(disableapertmacros no)\n\t\t\t(usegerberextensions no)\n\t\t\t(usegerberattributes yes)\n'
           '\t\t\t(usegerberadvancedattributes yes)\n\t\t\t(creategerberjobfile yes)\n'
           '\t\t\t(dashed_line_dash_ratio 12.000000)\n\t\t\t(dashed_line_gap_ratio 3.000000)\n'
           '\t\t\t(svgprecision 4)\n\t\t\t(plotframeref no)\n\t\t\t(mode 1)\n'
           '\t\t\t(useauxorigin no)\n\t\t\t(hpglpennumber 1)\n\t\t\t(hpglpenspeed 20)\n'
           '\t\t\t(hpglpendiameter 15.000000)\n\t\t\t(pdf_front_fp_property_popups yes)\n'
           '\t\t\t(pdf_back_fp_property_popups yes)\n\t\t\t(pdf_metadata yes)\n\t\t\t(pdf_single_document no)\n'
           '\t\t\t(dxfpolygonmode yes)\n\t\t\t(dxfimperialunits yes)\n\t\t\t(dxfusepcbnewfont yes)\n'
           '\t\t\t(psnegative no)\n\t\t\t(psa4output no)\n\t\t\t(plot_black_and_white yes)\n'
           '\t\t\t(sketchpadsonfab no)\n\t\t\t(plotpadnumbers no)\n\t\t\t(hidednponfab no)\n'
           '\t\t\t(sketchdnponfab yes)\n\t\t\t(crossoutdnponfab yes)\n\t\t\t(subtractmaskfromsilk no)\n'
           '\t\t\t(outputformat 1)\n\t\t\t(mirror no)\n\t\t\t(drillshape 1)\n\t\t\t(scaleselection 1)\n'
           '\t\t\t(outputdirectory "")\n\t\t)\n\t)',
           '\t(net 0 "")']
    for n in nets:
        hdr.append('\t(net %d "%s")' % (netcodes[n], n))

    body = []
    for ref, p in sorted(parts.items()):
        x, y, rot = pos[ref]
        body.append(place_footprint(p["fp"], ref, p["value"], ox + x, oy + y, rot,
                                    p["pads"], netcodes, dnp=p["dnp"]))
    for i, (mx, my) in enumerate([(hole_inset, hole_inset),
                                  (board_w - hole_inset, hole_inset),
                                  (hole_inset, board_h - hole_inset),
                                  (board_w - hole_inset, board_h - hole_inset)]):
        body.append(place_footprint("MountingHole:MountingHole_3.2mm_M3",
                                    "H%d" % (i + 1), "M3", ox + mx, oy + my, 0,
                                    {}, netcodes))
    cs = [(ox, oy), (ox + board_w, oy), (ox + board_w, oy + board_h), (ox, oy + board_h)]
    for a, b in zip(cs, cs[1:] + cs[:1]):
        body.append('\t(gr_line\n\t\t(start %.2f %.2f)\n\t\t(end %.2f %.2f)\n'
                    '\t\t(stroke\n\t\t\t(width 0.1)\n\t\t\t(type default)\n\t\t)\n'
                    '\t\t(layer "Edge.Cuts")\n\t\t(uuid "%s")\n\t)'
                    % (a[0], a[1], b[0], b[1], g.uid()))
    agnd = netcodes[gnd_net]
    for layer in ("F.Cu", "B.Cu"):
        body.append(
            '\t(zone\n\t\t(net %d)\n\t\t(net_name "%s")\n\t\t(layer "%s")\n\t\t(uuid "%s")\n'
            '\t\t(hatch edge 0.5)\n\t\t(connect_pads yes \n\t\t\t(clearance 0.4)\n\t\t)\n'
            '\t\t(min_thickness 0.25)\n\t\t(filled_areas_thickness no)\n'
            '\t\t(fill yes\n\t\t\t(thermal_gap 0.5)\n\t\t\t(thermal_bridge_width 0.5)\n\t\t)\n'
            '\t\t(polygon\n\t\t\t(pts\n\t\t\t\t(xy %.2f %.2f) (xy %.2f %.2f) (xy %.2f %.2f) (xy %.2f %.2f)\n\t\t\t)\n\t\t)\n\t)'
            % (agnd, gnd_net, layer, g.uid(),
               ox + 1, oy + 1, ox + board_w - 1, oy + 1,
               ox + board_w - 1, oy + board_h - 1, ox + 1, oy + board_h - 1))
    body.append('\t(embedded_fonts no)')
    body.append(')')
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(hdr + body) + "\n")
    print("Wrote %s: %d footprints, %d nets" % (out_path, len(parts) + 4, len(nets)))
